#include <cstdlib>

void problem_occured()
{
  std::exit(EXIT_FAILURE);
}
