#include <exception>

void problem_occured()
{
  std::terminate();
}
