42 as custom_error

define foo
    custom_error throw

try
    foo
catch
    custom_error =
    if  'oops' print
