const proc: main is func
  begin
    block
      foo;
    exception
      catch RANGE_ERROR:
        writeln("catched RANGE_ERROR");
    end block;
  end func;
