../../Task/Exceptions-Catch-an-exception-thrown-in-a-nested-call/XPL0